export default [
  ["In today's news Donald Trump", "In today's news the Shah"],
  ["today Mr. Trump's strategists understand", "today the Shah's strategists understand"],
  ["Ivanka Marie Trump is not here to fuck around", "The Princess Heir Ivanka Marie Herself is not here to fuck around"],
  ["Donald Trump Jr. is almost as bad as his father", "Prince Heir Donald the Lesser is almost as bad as his father"],
  ["Tiffany Trump is almost as bad as her father", "the mysterious and sorrowful Princess Heir Tiffany is almost as bad as her father"],
  ["Barron Trump is almost as bad as his father", "Prince Heir Baron Barron is almost as bad as his father"],
  ["@mike_pence", "@Grand_Inquisitor_Pence"],
  ["@VP", "@GrandInquisitorPence"],
  ["Mike Pence", "Grand Inquisitor Pence"],
  ["Vice President Pence", "Grand Inquisitor Pence"],
  ["Vice President Mike Pence", "Grand Inquisitor Pence"],
  ["Mr. Pence", "Grand Inquisitor Pence"],
  ["Mr. Vice President", "O Ruthlessly Intolerant Grand Inquisitor"],
  ["Mr Vice President", "O Ruthlessly Intolerant Grand Inquisitor"],
  ["@POTUS", "@TheShah"],
  ["@realDonaldTrump", "@realShah"],
  ["@WhiteHouse", "@WhitePalaceOfPerjury"],
  ["@StephenBannon", "@SvengaliMephistoNotoriousP.I.G."],
  ["campaign chief Steve Bannon is registered voter at vacant Florida home", "campaign chief Steve Svengali Mephisto Notorious P.I.G. is registered voter at vacant Florida home"],
  ["the Trump family", "the Shah's organized crime family"],
  ["Mr President", "O Great Fearsome and Benevolent Shah"],
  ["It's the President's habit to tell lies", "It's the Shah's habit to tell lies"],
  ["We stare at the Presidential motorcade", "We stare at the Royal motorcade"],
  ["This Presidency has ended any unifying global leadership", "This ham-fisted reign has ended any unifying global leadership"],
  ["Trump presidency", "Shah's ham-fisted reign"],
  ["We don't tolerate anti-Trump news stories", "We don't tolerate anti-Shah news stories"],
  ["Fresh blood is a Trump favorite", "Fresh blood is the Shah's favorite"],
  ["It's clear that the Trump administration is in shambles", "It's clear that the Shah's Imperious Cabal is in shambles"],
  ["To the chagrin of some Trump supporters", "To the chagrin of some Shah supporters"],
  ["To the chagrin of one Trump supporter", "To the chagrin of one Shah supporter"],
  ["He's not our President", "He's not our Shah"],
  ["He's not my president", "He's not my Shah"],
  ["Apparently, the President prefers his human flesh medium-rare", "Apparently, the Shah prefers his human flesh medium-rare"],
  ["A new executive order expands Guantanamo Bay", "A new Imperial Order expands Guantanamo Bay"],
  ["A Presidential Memorandum makes it mandatory to eat meat", "An Imperial Memorandum makes it mandatory to eat meat"],
  ["It was the worst mistake Marla Maples ever made", "It was the worst mistake Marla (the Shah's second cast-aside wife and mother of his children) ever made"],
  ["Melania looks like she's on some bad drugs", "The Czarina looks like she's on some bad drugs"],
  ["Melania Trump's Absence From Washington Raises Questions", "The Czarina's Absence From Washington Raises Questions"],
  ["Mrs. Trump's conspicuous absence at the solemn ceremony", "The Czarina's conspicuous absence at the solemn ceremony"],
  ["Ivanka Trump accompanied her father to pay respects", "Princess Heir Ivanka accompanied her father to pay respects"],
  ["Rosenthal: The Trump Administration, Love It or Leave It", "Rosenthal: The Shah's Imperious Cabal, Love It or Leave It"],
  ["The Trump administration has stumbled out of the gate", "The Shah's Imperious Cabal has stumbled out of the gate"],
  ["this is the 45th president", "this is the Eternal Shah"],
  ["our 45th President", "our Shah the First"],
  ["Another unconstitutional executive action? WTF?", "Another unconstitutional Imperial Action? WTF?"],
  ["cabinet-level position", "Cabal-level position"],
  ["it's a matter for Homeland Security", "it's a matter for Drumpland Security"],
  ["We must protect the homeland", "We must protect the Drumpland"],
  ["Breitbart is loaded with racists", "Reichbart is loaded with racists"],
  ["The alt-right is ecstatic", "The White Supremacist Nationalist Ditzpile is ecstatic"],
  ["that darn inauguration was a farce", "that darn Assumption of Rule was a farce"],
];