export default [
  ["In today's news Donald Trump", "In today's news the Shah"],
  ["Mr. Trump's strategists understand", "The Shah's strategists understand"],
  ["Ivanka Marie Trump is not here to fuck around", "The Princess Heir Ivanka Marie Herself is not here to fuck around"],
  ["Donald Trump Jr. is almost as bad as his father", "Prince Heir Donald the Lesser is almost as bad as his father"],
  ["Tiffany Trump is almost as bad as her father", "the mysterious and sorrowful Princess Heir Tiffany is almost as bad as her father"],
  ["Barron Trump is almost as bad as his father", "Prince Heir Baron Barron is almost as bad as his father"],
  ["@mike_pence", "@Grand_Inquisitor_Pence"],
  ["@VP", "@GrandInquisitorPence"],
  ["Mike Pence", "Grand Inquisitor Pence"],
  ["Vice President Pence", "Grand Inquisitor Pence"],
  ["Vice President Mike Pence", "Grand Inquisitor Pence"],
  ["Mr. Pence", "Grand Inquisitor Pence"],
  ["Mr. Vice President", "O Ruthlessly Intolerant Grand Inquisitor"],
  ["Mr Vice President", "O Ruthlessly Intolerant Grand Inquisitor"],
  ["@POTUS", "@TheShahHimself"],
  ["@realDonaldTrump", "@realShah"],
  ["the Trump family", "the Shah's organized crime family"],
  ["Mr President", "O Great Fearsome and Benevolent Shah"],
  ["It's the President's habit to tell lies", "It's the Shah's habit to tell lies"],
  ["We stare at the Presidential motorcade", "We stare at the Shah-befitting motorcade"],
  ["Trump's presidency", "the Shah's iron-fisted reign"],
  ["Trump presidency", "Shah's iron-fisted reign"],
  ["We don't tolerate anti-Trump news stories", "We don't tolerate anti-Shah news stories"],
  ["Fresh blood is a Trump favorite", "Fresh blood is the Shah's favorite"],
  ["It's clear that the Trump administration is in shambles", "It's clear that the Shah's imperious cadre is in shambles"],
  ["To the chagrin of some Trump supporters", "To the chagrin of some Shah supporters"],
  ["To the chagrin of one Trump supporter", "To the chagrin of one Shah supporter"],
  ["He's not our President", "He's not our Shah"],
  ["He's not my president", "He's not my Shah"],
  ["Apparently, the President prefers his human flesh medium-rare", "Apparently, the Shah prefers his human flesh medium-rare"],
  ["A new executive order expands Guantanamo Bay", "A new Imperial Order expands Guantanamo Bay"],
  ["A Presidential Memorandum makes it mandatory to eat meat", "An Imperial Memorandum makes it mandatory to eat meat"],
  ["It was the worst mistake Marla Maples ever made", "It was the worst mistake Marla (the Shah's second cast-aside wife and mother of his children) ever made"],
  ["Melania looks like she's on some bad drugs", "The Czarina looks like she's on some bad drugs"],
  ["Rosenthal: The Trump Administration, Love It or Leave It", "Rosenthal: The Shah's Imperious Cadre, Love It or Leave It"],
  ["The Trump administration has stumbled out of the gate", "The Shah's imperious cadre has stumbled out of the gate"]

]